# Generated by Django 4.2.7 on 2026-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0002_cart_cartitem_category_collection_contactmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
