# Generated by Django 4.2.7 on 2026-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0003_productimage_image_alter_productimage_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
