# Generated by Django 4.2.7 on 2026-04-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0004_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSizeInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=5,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_inventory",
                        to="djangoapp.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "size"],
                "unique_together": {("product", "size")},
            },
        ),
    ]
