# Generated by Django 4.2.7 on 2026-04-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0005_productsizeinventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inventory_count",
        ),
    ]
